//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter20.CustomerMaintenance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chapter20.CustomerMaintenance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while updating the customer.  Please try again..
        /// </summary>
        internal static string ErrorOccurredWhileUpdatingCustomer {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileUpdatingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer entry.  One of the required fields is empty.  Please fill in all fields..
        /// </summary>
        internal static string InvalidCustomerEntry {
            get {
                return ResourceManager.GetString("InvalidCustomerEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer ID entered.  Please try again.
        /// </summary>
        internal static string InvalidCustomerIDErrorMessage {
            get {
                return ResourceManager.GetString("InvalidCustomerIDErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Customer ID.
        /// </summary>
        internal static string InvalidCustomerIDTitle {
            get {
                return ResourceManager.GetString("InvalidCustomerIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry.
        /// </summary>
        internal static string InvalidEntryTitle {
            get {
                return ResourceManager.GetString("InvalidEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer information has been loaded.  Please Enter in the Customer ID and click on the &quot;Get Customer&quot; button.
        /// </summary>
        internal static string NoCustomerInformationErrorMessage {
            get {
                return ResourceManager.GetString("NoCustomerInformationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer information.
        /// </summary>
        internal static string NoCustomerInformationTitle {
            get {
                return ResourceManager.GetString("NoCustomerInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update customer..
        /// </summary>
        internal static string UnableToUpdateCustomer {
            get {
                return ResourceManager.GetString("UnableToUpdateCustomer", resourceCulture);
            }
        }
    }
}
